AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Learning Blocks API

  SAM Template for Learning Blocks

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  LearningBlocksAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: false

  AriesReportCardFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: learning_blocks_api/
      Handler: app.aries_report_card
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        demoAriesReportCard:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /LearningBlocksAPI/AriesReportCard
            Method: get
            RestApiId: !Ref LearningBlocksAPI

  AriesStudentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: learning_blocks_api/
      Handler: app.aries_students
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        demoAriesReportCard:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /LearningBlocksAPI/AriesStudents
            Method: get
            RestApiId: !Ref LearningBlocksAPI

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LearningBlocksApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${LearningBlocksAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/LearningBlocksAPI/"
  AriesReportCardFunction:
    Description: "Aries Report Card Lambda Function ARN"
    Value: !GetAtt AriesReportCardFunction.Arn
  AriesReportCardFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AriesReportCardFunctionRole.Arn
  AriesStudentsFunction:
    Description: "Aries Report Card Lambda Function ARN"
    Value: !GetAtt AriesStudentsFunction.Arn
  AriesReportStudentsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AriesStudentsFunctionRole.Arn
