version: '3.8'
services:
  fastapi:
    container_name: lb_api_01
    restart: unless-stopped
    build:
      context: ./python_backend
      dockerfile: ./Dockerfile
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    # command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - domain
      - project_name
      - postgres_server
      - postgres_user
      - postgres_password
      - postgres_db
      - pgadmin_listen_port
      - pgadmin_default_email
      - pgadmin_default_password
    # depends_on:
    #   - db
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s
  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USER=fastapi_traefik
  #     - POSTGRES_PASSWORD=fastapi_traefik
  #     - POSTGRES_DB=fastapi_traefik
  # caddy:
  #   container_name: lb_api_01
  #   restart: unless-stopped
  #   build:
  #     context: ./python_backend/caddy
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./data/caddy_data:/data
  #     - ./data/caddy_config:/config
  #   depends_on:
  #     - fastapi
  #   environment:
  #     PROXY_BACKEND: fastapi
  #     PROXY_PORT: 8000
  #     DOMAIN: ${DOMAIN}
  # volumes:
  #   caddy_data:
  #   caddy_config:
  #   postgres_data:
 
